name: Terra Framework CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#
#
#  publish:
#    needs: build
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#
#    steps:
#      - uses: actions/checkout@v3
