name: Terra Framework CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven for Aliyun
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>aliyun-private</id><username>${{ secrets.ALIYUN_USERNAME }}</username><password>${{ secrets.ALIYUN_PASSWORD }}</password></server></servers><mirrors><mirror><id>aliyun-mirror</id><mirrorOf>*</mirrorOf><url>https://maven.aliyun.com/nexus/content/groups/public</url></mirror></mirrors></settings>" > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B -s ~/.m2/settings.xml package --file pom.xml


  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven for Aliyun
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>aliyun-private</id><username>${{ secrets.ALIYUN_USERNAME }}</username><password>${{ secrets.ALIYUN_PASSWORD }}</password></server></servers><mirrors><mirror><id>aliyun-mirror</id><mirrorOf>*</mirrorOf><url>https://maven.aliyun.com/nexus/content/groups/public</url></mirror></mirrors></settings>" > ~/.m2/settings.xml
